@url=http://20.244.12.56:9725
@token=BchIC/Fm0YwxfUblCVV3Wbgt7aTi9alCI/iFzMTyvhbEaUrloq85Ig==

# Getting token
POST {{url}}/register
Content-Type: application/json

{
    "device_name": "Hello World",
    "device_uid": "asbcw-1s4"
}

# Get token wihtout device registraion
POST {{url}}/get-token
Content-Type: application/json

{
    "device_uid": "admin-123"
}

### All Devices
GET {{url}}/devices
x-token: {{token}}


### All Scales
GET {{url}}/scales
x-token: {{token}}

### All Scales only scale data
GET {{url}}/scales/compact
x-token: {{token}}

### Creating scale
POST {{url}}/scales
Content-Type: application/json
x-token: {{token}}

{
    "ss_uid": "abc-123",
    "oem_name": "1234",
    "model_name": "sansui"
}

### Assign product

GET {{url}}/scales/2
x-token: {{token}}


### Assign product

PATCH {{url}}/scales/8
Content-Type: application/json
x-token: {{token}}

{
    "product": 6,
    "weight_unit": "kg",
    "threshold_weight": 10,
    "allocation_weight": 100
}

### Delete Scale
DELETE {{url}}/scales/9
x-token: {{token}}

### Add Location
PUT {{url}}/scales/8/location
Content-Type: application/json
x-token: {{token}}

{
    "location_name": "first row",
    "fixture_no": 124,
    "row": 2
}

### Update weight
PUT {{url}}/scales/12/weight
Content-Type: application/json
x-token: {{token}}

{
    "weight_reading": 11,
    "reading_datetime": "2025-04-01 11:20:01"
}

### Getting Individual scale
GET {{url}}/scales/12/readings
x-token: {{token}}


### Find notification for ss
GET {{url}}/scales/8/notifications
x-token: {{token}}

### Get notifications
GET {{url}}/scales/notifications
x-token: {{token}}


### Find notification
GET {{url}}/scales/notifications/4
x-token: {{token}}


### Delete notification
DELETE {{url}}/scales/notifications/3
x-token: {{token}}

### Acknowledge notification
PUT {{url}}/scales/notifications/4/ack
x-token: {{token}}


### Getting all products
GET {{url}}/products
x-token: {{token}}

### Getting single product
GET {{url}}/products/100
x-token: {{token}}

### Adding Products
POST {{url}}/products
Content-Type: application/json
x-token: {{token}}

{
    "product_name": "Apple – Granny Smith Red",
    "product_plu": 3071
}

### Update Product
PATCH {{url}}/products/9
Content-Type: application/json
x-token: {{token}}

{
    "product_name": "Banana",
    "weight_unit": "lbs"
}


### Deleting Product
DELETE {{url}}/products/3
x-token: {{token}}


### Deleting Product
POST {{url}}/logout
x-token: {{token}}
