@url=http://98.70.27.104:9725
@token=5xzmZPP1cBuRpSJA31ADtHVErAjMiU7foGL81na5zzSOI0KKLVLM0g==



### Update weight scale 1
PUT {{url}}/scales/1/weight
Content-Type: application/json
x-token: {{token}}

{
    "weight_reading": 190,
    "reading_datetime": "2025-05-21 10:20:01"
}

### Update weight scale 1 without datetime
PUT {{url}}/scales/1/weight
Content-Type: application/json
x-token: {{token}}

{
    "weight_reading": 9
}

### Get a Scale
GET {{url}}/scales/1
x-token: {{token}}

### Getting Individual scale
GET {{url}}/scales/1/readings
x-token: {{token}}


### Find notification for ss
GET {{url}}/scales/1/notifications
x-token: {{token}}